# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 338ee6d246d993ec6a0badeefc2776b08e07ef4479cfd95f70072c2fa7d95e609b9f584e586d03691a706ae706f54643debee9cba62247def8e59b12d72ad2fe

test:
  secret_key_base: acd42bc4adaa2121f4d17e7824cb365e917ce3af686b8737ec1e9454c78403a52c7e262d5b81919cee84da5b9bd291d11a45210c8faa3cd345dd898beab4cae3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
